### ISSUE TITLE
Implementing karma-runner

### ISSUE THREAD

**Issue by MarkKrutik** [filerjs/filer#442]
The other day I was on Slack, I came up with an issue that the exist method is being deprecated. Robert suggested that we should implement the karma-coverage, which I think is an interesting idea. Please let me know what you guys think about this idea, it would be much appreciated. If you agree I want to try to install the karma-runner dependency using this command: npm install karma karma-coverage --save-dev. I will test if the dependency can even be installed and later we can add any additional tests related to karma-coverage. 

If you want more references this link tells you more about karma-coverage: https://github.com/karma-runner/karma-coverage. This is the same link that Robert shared on Slack. Thank you, Robert for offering such an interesting idea. I am willing to implement it, and I hope that most of us will be willing to work on this issue.
Thank you guys for reading this.

**Comment by humphd** [comment]
@MarkKrutik I think this is a great idea.  Quite a few students have asked for it.  If you want to give it a shot, I would be happy to review your PR.  I've played with this in the past, and run into some issues with `parceljs` and the way it bundles and minifies the code.  I think if we generate source maps for test builds, it *should* be possible.  Let's try it.

**Comment by humphd** [comment]
Go for it @MarkKrutik.  You'll want to play around with our settings in https://github.com/filerjs/filer/blob/master/karma.conf.js and https://github.com/filerjs/filer/blob/master/package.json.

**Comment by MarkKrutik** [comment]
I have installed karma by running this command:  npm install karma karma-coverage --save-dev. I have tried to fix the package.json and karma.conf.js, and it ran with the npm run karma-mocha. Is there anything else that you would recommend me to do?

**Comment by MarkKrutik** [comment]
I also ran this statement: istanbul cover index.js and got this message
=============================================================================
Writing coverage object [C:\Users\markk\filer\tests\dist\coverage\coverage.json]
Writing coverage reports at [C:\Users\markk\filer\tests\dist\coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 11.33% ( 710/6267 )
Branches     : 2.25% ( 119/5289 )
Functions    : 5% ( 125/2499 )
Lines        : 61.4% ( 105/171 )
================================================================================
C:\Users\markk\filer\tests\dist\index.js:9
__cov_da_OZ01mWkcCGFxHD8f19g.s['1']++;parcelRequire=function(e,r,n,t){__cov_da_OZ01mWkcCGFxHD8f19g.f['1']++;__cov_da_OZ01mWkcCGFxHD8f19g.s['2']++;var i=(__cov_da_OZ01mWkcCGFxHD8f19g.b['1'][0]++,'function'==typeof parcelRequire)&&(__cov_da_OZ01mWkcCGFxHD8f19g.b['1'][1]++,parcelRequire),o=(__cov_da_OZ01mWkcCGFxHD8f19g.b['2'][0]++,'function'==typeof require)&&(__cov_da_OZ01mWkcCGFxHD8f19g.b['2'][1]++,require);function u(n,t){__cov_da_OZ01mWkcCGFxHD8f19g.f['2']++;__cov_da_OZ01mWkcCGFxHD8f19g.s['4']++;if(!r[n]){__cov_da_OZ01mWkcCGFxHD8f19g.b['3'][0]++;__cov_da_OZ01mWkcCGFxHD8f19g.s['5']++;if(!e[n]){__cov_da_OZ01mWkcCGFxHD8f19g.b['4'][0]++;__cov_da_OZ01mWkcCGFxHD8f19g.s['6']++;var f=(__cov_da_OZ01mWkcCGFxHD8f19g.b['5'][0]++,'function'==typeof parcelRequire)&&(__cov_da_OZ01mWkcCGFxHD8f19g.b['5'][1]++,parcelRequire);__cov_da_OZ01mWkcCGFxHD8f19g.s['7']++;if((__cov_da_OZ01mWkcCGFxHD8f19g.b['7'][0]++,!t)&&(__cov_da_OZ01mWkcCGFxHD8f19g.b['7'][1]++,f)){__cov_da_OZ01mWkcCGFxHD8f

ReferenceError: describe is not defined
    at Object.parcelRequire.k419.../../src (C:\Users\markk\filer\tests\dist\index.js:9:495518)
    at u (C:\Users\markk\filer\tests\dist\index.js:9:2146)
    at p (C:\Users\markk\filer\tests\dist\index.js:9:2386)
    at Object.parcelRequire.Focm../spec/filer.spec (C:\Users\markk\filer\tests\dist\index.js:9:861267)
    at u (C:\Users\markk\filer\tests\dist\index.js:9:2146)
    at parcelRequire.rwRH (C:\Users\markk\filer\tests\dist\index.js:9:2962)
    at Object.<anonymous> (C:\Users\markk\filer\tests\dist\index.js:9:3932)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions.(anonymous function) [as .js] (C:\Users\markk\AppData\Roaming\npm\node_modules\istanbul\lib\hook.js:107:24)
    at Module.load (internal/modules/cjs/loader.js:599:32)

**Comment by MarkKrutik** [comment]
I am assuming from this message most of the code is not covered.

**Comment by humphd** [comment]
@MarkKrutik usually you wouldn't run `istanbul` directly, but rather let `karma` run it as a plugin.  You can see in their example at https://github.com/filerjs/filer/blob/master/package.json how they do it, by specifying a `coverage` reporter.
