### ISSUE TITLE
BUG: fs.mkdir does not recursively create parent directories when called with { recursive: true }

### ISSUE THREAD

**Issue by bcheidemann** [filerjs/filer#776]
Executing the following code:
```javascript
fs.mkdir('/test_dir/a/b', { recursive: true }, callback);
```

(when /test_dir does not exist)

Throws the error:
```
ENOENT: no such file or directory, '/test_dir'
    at new FilerError (tests.e31bb0bc.js:13841:18)
    at get_node_from_parent_directory_data (tests.e31bb0bc.js:16783:18)
    at IDBRequest.onsuccess (tests.e31bb0bc.js:13443:7)
```

This is not consistent with the [node.js documentation on fs.mkdir](https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback).

**Comment by humphd** [comment]
I started this in https://github.com/filerjs/filer/pull/479

**Comment by bcheidemann** [comment]
Duplicate of #414
